############################################################
# Site configurations
title : Multinerd
tagline: Site Tagline
author :
  name : Michael Hedaitulla
  email : blah@email.test
  github : multinerd
#  twitter : username
#  feedburner : feedname


url: "http://multinerd.github.io"
baseurl: ""
production_url: "http://multinerd.github.io" # Ideally, this would be your site.url + site.base_url
permalink: "/blog/articles/:year-:month-:day-:title.html"
path: # These paths are to the main pages. Some helpers refer to these paths; change them here if needed.
  atom_feed: /blog/feeds/atom.xml
  rss_feed: /blog/feeds/rss.xml
  json_feed: /blog/api/api.json
  blog: /blog/
  blog_archive: /blog/archive/
  blog_categories: /blog/categories/
  blog_tags: /blog/tags/
plugins:
  - jekyll-archives
  - jekyll-contentblocks
  - jekyll-paginate-v2
  - jekyll-sitemap
include:
  - _pages
exclude:
  - .jekyll-metadata
  - notes.md
  - serve.command
  - Gemfile
  - Gemfile.lock
  - /script
  - Rakefile
  - vendor

############################################################
# Pagination Settings
pagination:
  enabled: true
  debug: false
  title: ':title - Page :num'
  permalink: '/index:num.html'
  per_page: 2   # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  limit: 0      # Limit how many paginated pages to create (default: 0, means all)
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 10
    after: 10
#  collection: 'posts'  # The default document collection to paginate if nothing is specified ('posts' is default)
#  category: 'posts'    # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
#  tag: ''              # Optional, the default tag to use, omit to disable







highlighter: pygments


# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.3.0

  # All links will be namespaced by BASE_PATH if defined.
  # Links in your website should always be prefixed with {{BASE_PATH}}
  # however this value will be dynamically changed depending on your deployment situation.
  #
  # CNAME (http://yourcustomdomain.com)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Pages (http://username.github.io)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Project Pages (http://username.github.io/project-name)
  #
  #   A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
  #  REQUIRED! Set BASE_PATH to: http://username.github.io/project-name
  #
  # CAUTION:
  #   - When in Localhost, your site will run from root "/" regardless of BASE_PATH
  #   - Only the following values are false: ["", null, false]
  #   - When setting BASE_PATH it must be a valid url.
  #     This means always setting the protocol (http|https) or prefixing with "/"
  BASE_PATH : false






  # Settings for comments helper
  # Set 'provider' to the comment provider you want to use.
  # Set 'provider' to false to turn commenting off globally.
  #
  comments :
    provider : disqus
    disqus :
      short_name : jekyllbootstrap
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light
    duoshuo :
      short_name : jekyllbootstrap
   
  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #        
  analytics :
    provider : google
    gauges :
        site_id : 'SITE ID'
    google : 
        tracking_id : 'UA-***'
    googleUA :
        tracking_id : 'UA-***'
        property_name : 'PROPERTY NAME'
    getclicky :
      site_id : 
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'                   # the id of the site on Piwik

  # Settings for sharing helper. 
  # Sharing is for things like tweet, plusone, like, reddit buttons etc.
  # Set 'provider' to the sharing provider you want to use.
  # Set 'provider' to false to turn sharing off globally.
  #
  sharing :
    provider : false
    
  # Settings for all other include helpers can be defined by creating 
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"   
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.
  
